name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-node:
    runs-on: macos-latest
    container: node:16

    steps:
    - run: node --version
    - run: npm --version
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm test
    - run: node src/app.js